export default {
  task: {
    height: '95%',
    padding: '10px',
    backgroundColor: '#a8a996',
    borderRadius: '10px',
    border: '5px solid #f80d0d',
    width: '22%',
  },
  TextStringTask: {
    margin: '10px',
    height: '3%',
    padding: '5px',
    backgroundColor: '#a8a996',
    borderRadius: '10px',
    border: '5px solid #f80d0d',
  },
  FotoTask: {
    display: 'flex',
    justifyContent: 'space-between',
    height: '50px',
    padding: '5px',
  },
  IconFotoTask: {
    height: '55%',
    width: '10%',
    padding: '5px',
    borderRadius: '10px',
    border: '5px solid #f80d0d',
  },
  InputFotoTask: {
    margin: '0',
    height: '5%',
    width: '5px',
    padding: '5px',
    borderRadius: '10px',
    border: '5px solid #f80d0d',
  },
  HeaderTask: {
    margin: 'auto',
    height: '25%',
    padding: '5px',
    backgroundColor: '#a8a996',
    borderRadius: '10px',
    border: '5px solid #f80d0d',
  },
};
